################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
SM502/EthioCalender.obj: ../SM502/EthioCalender.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/EthioCalender.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/FixedActivities.obj: ../SM502/FixedActivities.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/FixedActivities.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/HardwareLimits.obj: ../SM502/HardwareLimits.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/HardwareLimits.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/I2C2.obj: ../SM502/I2C2.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/I2C2.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/I2C2EEPROM.obj: ../SM502/I2C2EEPROM.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/I2C2EEPROM.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/LCD_C.obj: ../SM502/LCD_C.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/LCD_C.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/LCD_C_Graphics.obj: ../SM502/LCD_C_Graphics.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/LCD_C_Graphics.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/LPBU.obj: ../SM502/LPBU.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/LPBU.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/Logger.obj: ../SM502/Logger.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/Logger.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/Queue.obj: ../SM502/Queue.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/Queue.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/Relay.obj: ../SM502/Relay.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/Relay.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/Schaduler.obj: ../SM502/Schaduler.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/Schaduler.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/SystemISRs.obj: ../SM502/SystemISRs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/SystemISRs.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/Tamper.obj: ../SM502/Tamper.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/Tamper.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/Tariff.obj: ../SM502/Tariff.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/Tariff.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/Test.obj: ../SM502/Test.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/Test.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/UI.obj: ../SM502/UI.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/UI.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/battery_monitor.obj: ../SM502/battery_monitor.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/battery_monitor.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/calibration.obj: ../SM502/calibration.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/calibration.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/errors.obj: ../SM502/errors.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/errors.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/self_diagnosis.obj: ../SM502/self_diagnosis.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/self_diagnosis.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

SM502/utilities.obj: ../SM502/utilities.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/abi/ti/ccsv7/ccs_base/msp430/include" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/aes" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/electricity_related_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/abstract_objects" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/PLC" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502/IEC62056" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/SM502" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/core" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng/DLMS/src" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-ng" --include_path="/home/abi/Desktop/Arada firmware v0003-new/SM502_ccs/emeter-toolkit" --include_path="/home/abi/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.3.LTS/include" --advice:power=all -g --undefine=_INLINE --define=__MSP430F6736__ --define=PHYSICAL_RELAY_DISCONNECT_ENABLED --define=CUSTOM_EMETER_H="emeter-1ph-neutral-6733_shunt.h" --define=CHUNK_SIZE=100 --define=DLMS_IEC_21 --define=DLMS --define=EEPROM_REV_2 --define=ALARM_ON_TAMPER --define=OPT_INT --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SM502/utilities.d" --obj_directory="SM502" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


